from __future__ import annotations

from core.domains.course import (
    add_assignment_asset,
    add_lecture_material,
    create_assignment,
    create_course,
    create_lecture,
    create_schedule,
    delete_course,
    get_course,
    link_course_document,
    list_course_documents,
    list_assignments,
    list_course_lectures,
    list_courses,
    list_lecture_materials,
    list_schedules,
    update_course,
    upsert_exam_asset,
)
from core.domains.research import (
    add_idea_dialogue,
    add_paper,
    confirm_idea,
    create_deck,
    create_experiment_plan,
    create_experiment_run,
    create_idea,
    create_paper_card,
    create_project,
    list_experiment_plans,
    list_experiment_runs,
    list_idea_dialogue,
    list_ideas,
    list_projects,
    list_project_papers,
    update_project,
)
from core.domains.timetable import create_event, list_events
from core.domains.todo import create_todo, list_todos, update_todo_status

__all__ = [
    "add_assignment_asset",
    "add_lecture_material",
    "create_assignment",
    "create_course",
    "create_deck",
    "create_event",
    "create_experiment_plan",
    "create_experiment_run",
    "create_idea",
    "create_lecture",
    "create_paper_card",
    "create_project",
    "create_schedule",
    "create_todo",
    "delete_course",
    "get_course",
    "link_course_document",
    "list_course_documents",
    "list_assignments",
    "list_course_lectures",
    "list_courses",
    "list_events",
    "list_lecture_materials",
    "list_experiment_plans",
    "list_experiment_runs",
    "list_idea_dialogue",
    "list_ideas",
    "list_project_papers",
    "list_projects",
    "list_schedules",
    "list_todos",
    "update_course",
    "update_project",
    "update_todo_status",
    "upsert_exam_asset",
]
